# Generated by Django 4.1.6 on 2023-02-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_outlet', '0004_author_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=60)),
                ('postal_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='addresse',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='books_outlet.adresse'),
        ),
    ]
