# Generated by Django 4.1.6 on 2023-02-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_outlet', '0006_country_book_published_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_books',
            field=models.ManyToManyField(to='books_outlet.country'),
        ),
    ]
